// Generated by Rcpp - do not edit by hand

#include <Rcpp.h>

using namespace Rcpp;

// kendall_info_cpp
NumericMatrix kendall_info_cpp(NumericMatrix r, IntegerMatrix inds);
RcppExport SEXP _RMallow_kendall_info_cpp(SEXP rSEXP, SEXP indsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type r(rSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type inds(indsSEXP);
    rcpp_result_gen = Rcpp::wrap(kendall_info_cpp(r, inds));
    return rcpp_result_gen;
END_RCPP
}
// combn_pairs_cpp
IntegerMatrix combn_pairs_cpp(int n);
RcppExport SEXP _RMallow_combn_pairs_cpp(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(combn_pairs_cpp(n));
    return rcpp_result_gen;
END_RCPP
}
// all_kendall_cpp
NumericMatrix all_kendall_cpp(NumericMatrix data_info, NumericMatrix seqs_info);
RcppExport SEXP _RMallow_all_kendall_cpp(SEXP data_infoSEXP, SEXP seqs_infoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data_info(data_infoSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type seqs_info(seqs_infoSEXP);
    rcpp_result_gen = Rcpp::wrap(all_kendall_cpp(data_info, seqs_info));
    return rcpp_result_gen;
END_RCPP
}
// all_seq_dists_cpp
IntegerVector all_seq_dists_cpp(NumericMatrix infos);
RcppExport SEXP _RMallow_all_seq_dists_cpp(SEXP infosSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type infos(infosSEXP);
    rcpp_result_gen = Rcpp::wrap(all_seq_dists_cpp(infos));
    return rcpp_result_gen;
END_RCPP
}
// update_r_sums_cpp
List update_r_sums_cpp(NumericMatrix infos, NumericMatrix z);
RcppExport SEXP _RMallow_update_r_sums_cpp(SEXP infosSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type infos(infosSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(update_r_sums_cpp(infos, z));
    return rcpp_result_gen;
END_RCPP
}
// estep_cpp
NumericMatrix estep_cpp(NumericMatrix all_dists, NumericVector lambda, NumericVector C, NumericVector p);
RcppExport SEXP _RMallow_estep_cpp(SEXP all_distsSEXP, SEXP lambdaSEXP, SEXP CSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type all_dists(all_distsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type C(CSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(estep_cpp(all_dists, lambda, C, p));
    return rcpp_result_gen;
END_RCPP
}
// next_table_cpp
NumericVector next_table_cpp(NumericVector last_table, int n_last);
RcppExport SEXP _RMallow_next_table_cpp(SEXP last_tableSEXP, SEXP n_lastSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type last_table(last_tableSEXP);
    Rcpp::traits::input_parameter< int >::type n_last(n_lastSEXP);
    rcpp_result_gen = Rcpp::wrap(next_table_cpp(last_table, n_last));
    return rcpp_result_gen;
END_RCPP
}
// simplify_sequences_cpp
NumericMatrix simplify_sequences_cpp(NumericMatrix rankings);
RcppExport SEXP _RMallow_simplify_sequences_cpp(SEXP rankingsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type rankings(rankingsSEXP);
    rcpp_result_gen = Rcpp::wrap(simplify_sequences_cpp(rankings));
    return rcpp_result_gen;
END_RCPP
}
// construct_seqs_cpp
List construct_seqs_cpp(NumericMatrix prefs, int n_abils);
RcppExport SEXP _RMallow_construct_seqs_cpp(SEXP prefsSEXP, SEXP n_abilsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type prefs(prefsSEXP);
    Rcpp::traits::input_parameter< int >::type n_abils(n_abilsSEXP);
    rcpp_result_gen = Rcpp::wrap(construct_seqs_cpp(prefs, n_abils));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RMallow_kendall_info_cpp", (DL_FUNC) &_RMallow_kendall_info_cpp, 2},
    {"_RMallow_combn_pairs_cpp", (DL_FUNC) &_RMallow_combn_pairs_cpp, 1},
    {"_RMallow_all_kendall_cpp", (DL_FUNC) &_RMallow_all_kendall_cpp, 2},
    {"_RMallow_all_seq_dists_cpp", (DL_FUNC) &_RMallow_all_seq_dists_cpp, 1},
    {"_RMallow_update_r_sums_cpp", (DL_FUNC) &_RMallow_update_r_sums_cpp, 2},
    {"_RMallow_estep_cpp", (DL_FUNC) &_RMallow_estep_cpp, 4},
    {"_RMallow_next_table_cpp", (DL_FUNC) &_RMallow_next_table_cpp, 2},
    {"_RMallow_simplify_sequences_cpp", (DL_FUNC) &_RMallow_simplify_sequences_cpp, 1},
    {"_RMallow_construct_seqs_cpp", (DL_FUNC) &_RMallow_construct_seqs_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_RMallow(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
