# Generated by Rcpp - do not edit by hand

#' @useDynLib RMallow, .registration = TRUE
#' @importFrom Rcpp sourceCpp
NULL

#' Compute pairwise comparison information for Kendall's distance (C++ version)
#' @keywords internal
kendall_info_cpp <- function(r, inds) {
    .Call('_RMallow_kendall_info_cpp', PACKAGE = 'RMallow', r, inds)
}

#' Generate pairwise column indices (C++ version)
#' @keywords internal
combn_pairs_cpp <- function(n) {
    .Call('_RMallow_combn_pairs_cpp', PACKAGE = 'RMallow', n)
}

#' Compute Kendall distances between rankings and reference sequences (C++ version)
#' @keywords internal
all_kendall_cpp <- function(data_info, seqs_info) {
    .Call('_RMallow_all_kendall_cpp', PACKAGE = 'RMallow', data_info, seqs_info)
}

#' Compute distances to canonical ordering (C++ version)
#' @keywords internal
all_seq_dists_cpp <- function(infos) {
    .Call('_RMallow_all_seq_dists_cpp', PACKAGE = 'RMallow', infos)
}

#' Compute weighted sums for UpdateR (C++ version)
#' @keywords internal
update_r_sums_cpp <- function(infos, z) {
    .Call('_RMallow_update_r_sums_cpp', PACKAGE = 'RMallow', infos, z)
}

#' E-Step computation (C++ version)
#' @keywords internal
estep_cpp <- function(all_dists, lambda, C, p) {
    .Call('_RMallow_estep_cpp', PACKAGE = 'RMallow', all_dists, lambda, C, p)
}

#' NextTable computation (C++ version)
#' @keywords internal
next_table_cpp <- function(last_table, n_last) {
    .Call('_RMallow_next_table_cpp', PACKAGE = 'RMallow', last_table, n_last)
}

#' SimplifySequences (C++ version)
#' @keywords internal
simplify_sequences_cpp <- function(rankings) {
    .Call('_RMallow_simplify_sequences_cpp', PACKAGE = 'RMallow', rankings)
}

#' ConstructSeqs (C++ version)
#' @keywords internal
construct_seqs_cpp <- function(prefs, n_abils) {
    .Call('_RMallow_construct_seqs_cpp', PACKAGE = 'RMallow', prefs, n_abils)
}
